//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFID.RFIDInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>MTI (TM)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SupportedReaders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SupportedReaders"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Internal")]
        public string Mode {
            get {
                return ((string)(this["Mode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int ReaderRequestPageSize {
            get {
                return ((int)(this["ReaderRequestPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int PacketStreamPageSize {
            get {
                return ((int)(this["PacketStreamPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int ReaderCommandPageSize {
            get {
                return ((int)(this["ReaderCommandPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int ReaderCyclePageSize {
            get {
                return ((int)(this["ReaderCyclePageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int AntennaCyclePageSize {
            get {
                return ((int)(this["AntennaCyclePageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TagInventoryPageSize {
            get {
                return ((int)(this["TagInventoryPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int InventoryRoundPageSize {
            get {
                return ((int)(this["InventoryRoundPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int TagReadPageSize {
            get {
                return ((int)(this["TagReadPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int BadPacketPageSize {
            get {
                return ((int)(this["BadPacketPageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PropertyBagPageSize {
            get {
                return ((int)(this["PropertyBagPageSize"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LibraryMode {
            get {
                return ((int)(this["LibraryMode"]));
            }
            set {
                this["LibraryMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeBadCRC {
            get {
                return ((bool)(this["IncludeBadCRC"]));
            }
            set {
                this["IncludeBadCRC"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int MaxVirtualAntennas {
            get {
                return ((int)(this["MaxVirtualAntennas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxAllowedProfiles {
            get {
                return ((int)(this["MaxAllowedProfiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MaxFrequencyBands {
            get {
                return ((int)(this["MaxFrequencyBands"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int ReadRatePageSize {
            get {
                return ((int)(this["ReadRatePageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int InventoryCyclePageSize {
            get {
                return ((int)(this["InventoryCyclePageSize"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RadioOperationMode {
            get {
                return ((int)(this["RadioOperationMode"]));
            }
            set {
                this["RadioOperationMode"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0,ENABLED,300,2000,8192,0,0;
1,DISABLED,300,2000,8192,1,1;
2,DISABLED,300,2000,8192,3,3;
3,DISABLED,300,2000,8192,3,3;
4,DISABLED,300,2000,8192,3,3;
5,DISABLED,300,2000,8192,3,3;
6,DISABLED,300,2000,8192,3,3;
7,DISABLED,300,2000,8192,3,3;
8,DISABLED,300,2000,8192,3,3;
9,DISABLED,300,2000,8192,3,3;
10,DISABLED,300,2000,8192,3,3;
11,DISABLED,300,2000,8192,3,3;
12,DISABLED,300,2000,8192,3,3;
13,DISABLED,300,2000,8192,3,3;
14,DISABLED,300,2000,8192,3,3;
15,DISABLED,300,2000,8192,3,3;")]
        public string DefaultAntennaSettings {
            get {
                return ((string)(this["DefaultAntennaSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0,ENABLED,3663,24,20,2,2,0;
1,ENABLED,3661,24,20,2,2,0;
2,ENABLED,3613,24,20,2,2,0;
3,ENABLED,3707,24,20,2,2,0;
4,ENABLED,3705,24,20,2,2,0;
5,ENABLED,3617,24,20,2,2,0;
6,ENABLED,3709,24,20,2,2,0;
7,ENABLED,3681,24,20,2,2,0;
8,ENABLED,3677,24,20,2,2,0;
9,ENABLED,3637,24,20,2,2,0;
10,ENABLED,3675,24,20,2,2,0;
11,ENABLED,3671,24,20,2,2,0;
12,ENABLED,3621,24,20,2,2,0;
13,ENABLED,3619,24,20,2,2,0;
14,ENABLED,3701,24,20,2,2,0;
15,ENABLED,3687,24,20,2,2,0;
16,ENABLED,3659,24,20,2,2,0;
17,ENABLED,3627,24,20,2,2,0;
18,ENABLED,3655,24,20,2,2,0;
19,ENABLED,3689,24,20,2,2,0;
20,ENABLED,3645,24,20,2,2,0;
21,ENABLED,3647,24,20,2,2,0;
22,ENABLED,3615,24,20,2,2,0;
23,ENABLED,3635,24,20,2,2,0;
24,ENABLED,3623,24,20,2,2,0;
25,ENABLED,3649,24,20,2,2,0;
26,ENABLED,3625,24,20,2,2,0;
27,ENABLED,3669,24,20,2,2,0;
28,ENABLED,3657,24,20,2,2,0;
29,ENABLED,3629,24,20,2,2,0;
30,ENABLED,3673,24,20,2,2,0;
31,ENABLED,3665,24,20,2,2,0;
32,ENABLED,3641,24,20,2,2,0;
33,ENABLED,3643,24,20,2,2,0;
34,ENABLED,3631,24,20,2,2,0;
35,ENABLED,3699,24,20,2,2,0;
36,ENABLED,3639,24,20,2,2,0;
37,ENABLED,3679,24,20,2,2,0;
38,ENABLED,3667,24,20,2,2,0;
39,ENABLED,3653,24,20,2,2,0;
40,ENABLED,3695,24,20,2,2,0;
41,ENABLED,3633,24,20,2,2,0;
42,ENABLED,3703,24,20,2,2,0;
43,ENABLED,3651,24,20,2,2,0;
44,ENABLED,3697,24,20,2,2,0;
45,ENABLED,3685,24,20,2,2,0;
46,ENABLED,3683,24,20,2,2,0;
47,ENABLED,3691,24,20,2,2,0;
48,ENABLED,3611,24,20,2,2,0;
49,ENABLED,3693,24,20,2,2,0")]
        public string DefaultChannels_FCC {
            get {
                return ((string)(this["DefaultChannels_FCC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,DISABLED,8651,60,20,4,4,0;\r\n1,DISABLED,8653,60,20,4,4,0;\r\n2,DISABLED,8655,60,20" +
            ",4,4,0;\r\n3,ENABLED,8657,60,20,4,4,0;\r\n4,ENABLED,8659,60,20,4,4,0;\r\n5,ENABLED,866" +
            "1,60,20,4,4,0;\r\n6,ENABLED,8663,60,20,4,4,0;\r\n7,ENABLED,8665,60,20,4,4,0;\r\n8,ENAB" +
            "LED,8667,60,20,4,4,0;\r\n9,ENABLED,8669,60,20,4,4,0;\r\n10,ENABLED,8671,60,20,4,4,0;" +
            "\r\n11,ENABLED,8673,60,20,4,4,0;\r\n12,ENABLED,8675,60,20,4,4,0;\r\n13,DISABLED,8677,6" +
            "0,20,4,4,0;\r\n14,DISABLED,8679,60,20,4,4,0;\r\n15,DISABLED,3687,24,20,2,2,0;\r\n16,DI" +
            "SABLED,3659,24,20,2,2,0;\r\n17,DISABLED,3627,24,20,2,2,0;\r\n18,DISABLED,3655,24,20," +
            "2,2,0;\r\n19,DISABLED,3689,24,20,2,2,0;\r\n20,DISABLED,3645,24,20,2,2,0;\r\n21,DISABLE" +
            "D,3647,24,20,2,2,0;\r\n22,DISABLED,3615,24,20,2,2,0;\r\n23,DISABLED,3635,24,20,2,2,0" +
            ";\r\n24,DISABLED,3623,24,20,2,2,0;\r\n25,DISABLED,3649,24,20,2,2,0;\r\n26,DISABLED,362" +
            "5,24,20,2,2,0;\r\n27,DISABLED,3669,24,20,2,2,0;\r\n28,DISABLED,3657,24,20,2,2,0;\r\n29" +
            ",DISABLED,3629,24,20,2,2,0;\r\n30,DISABLED,3673,24,20,2,2,0;\r\n31,DISABLED,3665,24," +
            "20,2,2,0;\r\n32,DISABLED,3641,24,20,2,2,0;\r\n33,DISABLED,3643,24,20,2,2,0;\r\n34,DISA" +
            "BLED,3631,24,20,2,2,0;\r\n35,DISABLED,3699,24,20,2,2,0;\r\n36,DISABLED,3639,24,20,2," +
            "2,0;\r\n37,DISABLED,3679,24,20,2,2,0;\r\n38,DISABLED,3667,24,20,2,2,0;\r\n39,DISABLED," +
            "3653,24,20,2,2,0;\r\n40,DISABLED,3695,24,20,2,2,0;\r\n41,DISABLED,3633,24,20,2,2,0;\r" +
            "\n42,DISABLED,3703,24,20,2,2,0;\r\n43,DISABLED,3651,24,20,2,2,0;\r\n44,DISABLED,3697," +
            "24,20,2,2,0;\r\n45,DISABLED,3685,24,20,2,2,0;\r\n46,DISABLED,3683,24,20,2,2,0;\r\n47,D" +
            "ISABLED,3691,24,20,2,2,0;\r\n48,DISABLED,3611,24,20,2,2,0;\r\n49,DISABLED,3693,24,20" +
            ",2,2,0")]
        public string DefaultChannels_ETSI {
            get {
                return ((string)(this["DefaultChannels_ETSI"]));
            }
            set {
                this["DefaultChannels_ETSI"] = value;
            }
        }
    }
}
